name: massivefold-1.5.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - absl-py==1.0.0
      - biopython==1.81
      - matplotlib==3.10.0
      - seaborn==0.13.2
      - numpy==2.2.3
      - pandas==2.2.3
      - scipy==1.15.2
      - glypy==1.0.14
