name: massivefold
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - pip:
      - absl-py==1.0.0
      - biopython==1.79
      - matplotlib==3.7.2
      - seaborn==0.13.2
      - glypy
