name: massivefold-1.2.1
channels:
  - conda-forge
  - bioconda
  - nvidia
  - defaults
dependencies:
  - colabfold=1.5.5
  - hmmer=3.3.2
  - hhsuite=3.3.0
  - openmm=7.7.0
  - kalign2
  - cuda-nvcc
  - pip
  - pip:
      - absl-py==1.0.0
      - biopython==1.79
      - matplotlib==3.7.2
      - seaborn==0.13.2
      - git+https://github.com/GBLille/AFmassive@v1.1.1
